apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: employee-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend

        image: edlabadkarsameer/k8s-practice-backend:v1

        imagePullPolicy: Always

        ports:
        - containerPort: 8000

        env:
        - name: DB_URL
          value: postgresql://admin:password@postgres-service:5432/employees

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "256Mi"

        livenessProbe:
          httpGet:
            path: /
            port: 8000

          initialDelaySeconds: 15

        readinessProbe:
          httpGet:
            path: /
            port: 8000

          initialDelaySeconds: 10